version: "2"

services:
  nginx8:
    build: .
    ports:
      - 443:443
    network_mode: "host"
    volumes:
      - ./scripts/start.sh:/start.sh
      # - ./scripts/run_letsencrypt.sh:/run_letsencrypt.sh
    environment:
      - NGINX_SERVER_PORT=80
      - NGINX_SERVER_NAME=alex.nitra.ua
      - DOMAIN=localhost
      - EMAIL=v.branitsky@nitralabs.com
      - COMPRESSION=gzip
    entrypoint: /start.sh
    # entrypoint: /run_letsencrypt.sh
